"""
Trading Scanner — Indian stock swing-trading scanner and research platform.

DISCLAIMER: This software is for educational and research purposes only.
Historical backtests do not guarantee future performance.
No signal generated by this system guarantees profit.
Always do your own research before making investment decisions.
"""

__version__ = "0.1.0"
