"""Signal model — stores generated trading signals with scoring and reasoning."""

from __future__ import annotations

import datetime
from decimal import Decimal

from sqlalchemy import DateTime, ForeignKey, Index, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from scanner.models.base import Base


class Signal(Base):
    """
    Represents a trading signal generated by a strategy.

    Each signal includes a quality score (0-100), entry/stop/target levels,
    risk/reward ratio, and human-readable reasoning. The score represents
    how well the setup matches the defined strategy criteria — it is NOT
    a probability of profit.
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    instrument_id: Mapped[int] = mapped_column(
        ForeignKey("instruments.id", ondelete="CASCADE"), nullable=False
    )
    timestamp: Mapped[datetime.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    strategy: Mapped[str] = mapped_column(String(50), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False, default="LONG")
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    entry: Mapped[Decimal] = mapped_column(Numeric(12, 4), nullable=False)
    entry_high: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    stop_loss: Mapped[Decimal] = mapped_column(Numeric(12, 4), nullable=False)
    target1: Mapped[Decimal] = mapped_column(Numeric(12, 4), nullable=False)
    target2: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    risk_reward: Mapped[Decimal] = mapped_column(Numeric(6, 2), nullable=False)
    confidence: Mapped[str | None] = mapped_column(String(20), nullable=True)
    reasons: Mapped[str] = mapped_column(Text, nullable=False)
    invalidation: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACTIVE")
    market_regime: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # Relationships
    instrument: Mapped[Instrument] = relationship(  # noqa: F821
        "Instrument", back_populates="signals"
    )

    __table_args__ = (
        Index("ix_signals_strategy_timestamp", "strategy", "timestamp"),
        Index("ix_signals_status", "status"),
    )

    def __repr__(self) -> str:
        return (
            f"<Signal(instrument_id={self.instrument_id}, strategy={self.strategy}, "
            f"score={self.score}, direction={self.direction})>"
        )
